global:
  scrape_interval: 500m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 500m
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:8083']

remote_write:
  - url: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
    basic_auth:
      username: "1937430"
      password: "glc_eyJvIjoiMTI5MDI0NCIsIm4iOiJzdGFjay0xMTEwMjEzLWhtLXdyaXRlLWJhdGF0YXNfdG9rZW4iLCJrIjoidHhtYjBGM3pHOTcwaU56STY1SzZQMTZIIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0="
